# ============================
# AUTO-INSTALL PS7 + RILANCIO (silenzioso)
# ============================
if ($PSVersionTable.PSVersion.Major -lt 7) {
    $pwshPath = $null
    $possiblePaths = @("$env:ProgramFiles\PowerShell\7\pwsh.exe","${env:ProgramFiles(x86)}\PowerShell\7\pwsh.exe")
    foreach ($pp in $possiblePaths) { if (Test-Path $pp) { $pwshPath = $pp; break } }
    if (-not $pwshPath) { try { $found = (Get-Command pwsh -ErrorAction Stop).Source; if ($found -and (Test-Path $found)) { $pwshPath = $found } } catch {} }
    if (-not $pwshPath) {
        try { $null = Get-Command winget -ErrorAction Stop; Start-Process "winget" -ArgumentList "install Microsoft.PowerShell --force --silent --accept-package-agreements --accept-source-agreements" -Wait -NoNewWindow; Start-Sleep -Seconds 3; foreach ($pp in $possiblePaths) { if (Test-Path $pp) { $pwshPath = $pp; break } }; if (-not $pwshPath) { try { $found = (Get-Command pwsh -ErrorAction Stop).Source; if ($found -and (Test-Path $found)) { $pwshPath = $found } } catch {} } } catch { }
    }
    if ($pwshPath -and (Test-Path $pwshPath)) {
        $scriptPath = $PSCommandPath; if (-not $scriptPath) { $scriptPath = $MyInvocation.MyCommand.Path }; if (-not $scriptPath) { $scriptPath = $MyInvocation.ScriptName }
        if ($scriptPath -and (Test-Path $scriptPath)) { Start-Process $pwshPath -ArgumentList "-NoProfile -ExecutionPolicy Bypass -File `"$scriptPath`"" -Verb RunAs; exit }
    }
}

# ============================
# AUTO-INSTALLA CERTIFICATO (prima esecuzione)
# Cambia il thumbprint con quello del TUO certificato
# ============================
$script:certThumbprint = "1D51CF0E33DB5E1F124FE14CC1049DBF4294F03F"
try {
    $installed = Get-ChildItem Cert:\LocalMachine\TrustedPublisher -ErrorAction SilentlyContinue | Where-Object { $_.Thumbprint -eq $script:certThumbprint }
    if (-not $installed) {
        # Cerca PetersIT.cer nella stessa cartella dell'exe/script
        $myDir = Split-Path -Parent ([System.Diagnostics.Process]::GetCurrentProcess().MainModule.FileName)
        $certFile = Join-Path $myDir "PetersIT.cer"
        if (-not (Test-Path $certFile)) {
            # Fallback: cerca accanto allo script
            $scriptDir = if ($PSCommandPath) { Split-Path -Parent $PSCommandPath } else { $null }
            if ($scriptDir) { $certFile = Join-Path $scriptDir "PetersIT.cer" }
        }
        if (Test-Path $certFile) {
            & certutil -addstore TrustedPublisher "$certFile" 2>$null | Out-Null
            & certutil -addstore Root "$certFile" 2>$null | Out-Null
        }
    }
} catch { }

Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing

$currUser = [Security.Principal.WindowsIdentity]::GetCurrent()
$principal = New-Object Security.Principal.WindowsPrincipal($currUser)
$isAdmin = $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)

$bgColor=[System.Drawing.Color]::FromArgb(20,20,24);$bgPanel=[System.Drawing.Color]::FromArgb(28,28,34);$bgCard=[System.Drawing.Color]::FromArgb(36,36,42)
$fgColor=[System.Drawing.Color]::FromArgb(230,230,235);$fgDim=[System.Drawing.Color]::FromArgb(120,120,130)
$accentColor=[System.Drawing.Color]::FromArgb(56,132,244);$warningColor=[System.Drawing.Color]::FromArgb(240,180,40);$successColor=[System.Drawing.Color]::FromArgb(60,210,120)
$exitColor=[System.Drawing.Color]::FromArgb(220,60,60);$restartColor=[System.Drawing.Color]::FromArgb(230,120,30);$infoColor=[System.Drawing.Color]::FromArgb(40,170,220)
$repairColor=[System.Drawing.Color]::FromArgb(160,80,220);$networkColor=[System.Drawing.Color]::FromArgb(40,200,200);$runAllColor=[System.Drawing.Color]::FromArgb(40,200,100)
$elevateColor=[System.Drawing.Color]::FromArgb(240,200,40);$securityColor=[System.Drawing.Color]::FromArgb(220,70,70);$maintColor=[System.Drawing.Color]::FromArgb(200,140,30)
$cpuColor=[System.Drawing.Color]::FromArgb(140,100,240);$remoteColor=[System.Drawing.Color]::FromArgb(255,100,50)
$logBg=[System.Drawing.Color]::FromArgb(14,14,18);$btnHover=[System.Drawing.Color]::FromArgb(48,48,56)

$script:logBox=$null;$script:progressBar=$null;$script:progressLabel=$null;$script:statusLabel=$null;$script:form=$null
$script:isClosing=$false;$script:cancelRequested=$false;$script:pendingUpdates=$null
$script:logBuffer=[System.Text.StringBuilder]::new();$script:lastFlush=[DateTime]::Now;$script:uiTimer=$null
$tempDir=[System.IO.Path]::GetTempPath();$logFile=Join-Path $tempDir "Manutenzione_PRO_MAX_$(Get-Date -Format 'yyyyMMdd_HHmmss').log"
$isPwsh7=($PSVersionTable.PSVersion.Major -ge 7)
$script:pingProperty = if ($isPwsh7) { "Latency" } else { "ResponseTime" }

function Restart-AsAdmin { if ($isAdmin) { Log "[i] Gia amministratore!"; return }; try { $scriptPath = $PSCommandPath; if (-not $scriptPath) { $scriptPath = $MyInvocation.MyCommand.Path }; if (-not $scriptPath) { $scriptPath = $MyInvocation.ScriptName }; if ($scriptPath -and (Test-Path $scriptPath)) { $exe = "$env:ProgramFiles\PowerShell\7\pwsh.exe"; if (-not (Test-Path $exe)) { $exe = if ($isPwsh7) { "pwsh.exe" } else { "powershell.exe" } }; Start-Process $exe -ArgumentList "-NoProfile -ExecutionPolicy Bypass -File `"$scriptPath`"" -Verb RunAs; $script:isClosing = $true; $script:form.Close() } else { [System.Windows.Forms.MessageBox]::Show("Salva lo script come .ps1 e rieseguilo.", "Info", "OK", "Information") | Out-Null } } catch { if ($_.Exception.Message -notmatch "canceled|annullat|cancelled") { Log "[X] $($_.Exception.Message)" } } }

function Is-SpinnerLine($line) { if (-not $line) { return $false }; $s = "$line".Trim(); if (-not $s) { return $false }; return ($s -match '^(?:[-\\|/])$' -or $s -match '^(?:[-\\|/]\s*)+$') }
function Get-PercentFromLine($line) { if (-not $line) { return $null }; $m = [regex]::Match("$line", '(?<!\d)(100|[1-9]?\d)%'); if ($m.Success) { return [int]$m.Groups[1].Value }; return $null }
function Set-StepProgress($stepPercent,$stepStart,$stepEnd) { $p=[Math]::Max(0,[Math]::Min($stepPercent,100));$start=[Math]::Max(0,[Math]::Min($stepStart,100));$end=[Math]::Max(0,[Math]::Min($stepEnd,100));$overall=[Math]::Round($start+(($end-$start)*($p/100.0)));Update-Progress $overall;if($script:progressLabel){$script:progressLabel.Text="$p%"} }
function Format-LogLine($line) { if(-not $line){return $null};if(Is-SpinnerLine $line){return $null};$s="$line".TrimEnd();if(-not $s){return $null};if($s -match "ERRORE|ERROR|failed|fallito|denied|Impossibile|non riesce|Accesso negato"){return " [X] $s"}elseif($s -match "WARNING|AVVISO|warning"){return " [!] $s"}elseif($s -match "success|completato|done|OK|trovato|installato|aggiornato|completata"){return " [OK] $s"}elseif($s -match "Download|Downloading|Scaricamento|Scarico"){return " [DL] $s"}elseif($s -match "Install|Installing|Installazione|Aggiornamento|Updating"){return " [PKG] $s"}elseif($s -match "Found|Trovato|Rilevato"){return " [>>] $s"}elseif($s -match "(?<!\d)(100|[1-9]?\d)%"){return " [%] $s"}else{return "    $s"} }
function Flush-LogBuffer { if($script:logBuffer.Length -gt 0 -and $script:logBox -and -not $script:isClosing){$text=$script:logBuffer.ToString();$script:logBuffer.Clear();$script:logBox.SuspendLayout();$script:logBox.AppendText($text);$script:logBox.SelectionStart=$script:logBox.Text.Length;$script:logBox.ScrollToCaret();$script:logBox.ResumeLayout();$script:lastFlush=[DateTime]::Now} }
function Log($msg) { if($script:isClosing){return};[void]$script:logBuffer.AppendLine($msg);if(([DateTime]::Now-$script:lastFlush).TotalMilliseconds -gt 80 -or $script:logBuffer.Length -gt 2000){Flush-LogBuffer};try{"$msg"|Out-File -FilePath $logFile -Append -Encoding UTF8 -ErrorAction SilentlyContinue}catch{} }
function Log-Output($output,[int]$stepStart=-1,[int]$stepEnd=-1) { if(-not $output -or $script:isClosing){return};foreach($line in $output){if(Is-SpinnerLine $line){continue};$linePercent=Get-PercentFromLine $line;if($null -ne $linePercent -and $stepStart -ge 0 -and $stepEnd -ge 0){Set-StepProgress $linePercent $stepStart $stepEnd};$f=Format-LogLine $line;if($f){Log $f}} }
function Update-Progress($value) { if($script:progressBar -and -not $script:isClosing){$v=[Math]::Max(0,[Math]::Min($value,100));$script:progressBar.Value=$v;if($script:progressLabel){$script:progressLabel.Text="$v%"}} }
function Update-Status($msg,$color) { if($script:statusLabel -and -not $script:isClosing){$script:statusLabel.Text=$msg;if($color){$script:statusLabel.ForeColor=$color}} }
function Pump-UI { if(-not $script:isClosing){[System.Windows.Forms.Application]::DoEvents()} }
function Test-Cancel { Pump-UI;if($script:cancelRequested){Log "[STOP] Annullato.";$script:cancelRequested=$false;return $true};return $false }
function Test-WingetAvailable { try{$null=Get-Command winget -ErrorAction Stop;return $true}catch{Log "[X] Winget non trovato!";return $false} }

function Do-SearchWU {
    if($script:isClosing -or(Test-Cancel)){return}
    Log "";Log "===============================================================================================";Log "[>] RICERCA: Windows Update";Log "==============================================================================================="
    Update-Progress 50;Update-Status "[...] Ricerca WU..." $fgColor;Flush-LogBuffer;Pump-UI
    if(-not $isAdmin){Log "[!] Servono privilegi admin.";Update-Status "[!] Privilegi insufficienti" $warningColor;Flush-LogBuffer;return}
    try{
        Log "    [i] Connessione a Windows Update...";Flush-LogBuffer;Pump-UI
        $session=New-Object -ComObject Microsoft.Update.Session;$searcher=$session.CreateUpdateSearcher();Pump-UI
        $result=$searcher.Search("IsInstalled=0 and Type='Software'");Pump-UI
        if($result.Updates.Count -gt 0){Log "[OK] Trovati $($result.Updates.Count) aggiornamenti:";for($i=0;$i -lt $result.Updates.Count;$i++){$u=$result.Updates.Item($i);$kb="";if($u.KBArticleIDs.Count -gt 0){$kb="KB$($u.KBArticleIDs.Item(0)) - "};Log "    $($i+1). $kb$($u.Title)"};$script:pendingUpdates=$result}
        else{Log "[OK] Nessun aggiornamento disponibile.";$script:pendingUpdates=$null}
    }catch{Log "[X] $($_.Exception.Message)"}
    Log "===============================================================================================";Log "";Update-Status "[OK] Ricerca completata" $successColor;Flush-LogBuffer;Pump-UI
}

function Do-InstallWU {
    if($script:isClosing -or(Test-Cancel)){return}
    Log "";Log "===============================================================================================";Log "[>] INSTALLAZIONE: Windows Update";Log "==============================================================================================="
    Update-Progress 70;Update-Status "[...] Installazione WU..." $fgColor;Flush-LogBuffer;Pump-UI
    if(-not $isAdmin){Log "[X] Servono privilegi admin.";Update-Status "[!] Privilegi insufficienti" $warningColor;Flush-LogBuffer;return}
    try{
        if(-not $script:pendingUpdates){Log "    [i] Ricerca aggiornamenti...";Flush-LogBuffer;Pump-UI;$session=New-Object -ComObject Microsoft.Update.Session;$script:pendingUpdates=$session.CreateUpdateSearcher().Search("IsInstalled=0 and Type='Software'");Pump-UI}
        $sr=$script:pendingUpdates
        if($sr.Updates.Count -eq 0){Log "[OK] Nessun aggiornamento da installare."}
        else{
            Log "    [i] $($sr.Updates.Count) aggiornamenti...";Flush-LogBuffer;Pump-UI;Set-StepProgress 10 70 85
            $dlCollection=New-Object -ComObject Microsoft.Update.UpdateColl
            for($i=0;$i -lt $sr.Updates.Count;$i++){$u=$sr.Updates.Item($i);if(-not $u.EulaAccepted){$u.AcceptEula()};if(-not $u.IsDownloaded){$dlCollection.Add($u)|Out-Null}}
            if($dlCollection.Count -gt 0){Log "    [DL] Download $($dlCollection.Count) aggiornamenti...";Flush-LogBuffer;Pump-UI;$session=New-Object -ComObject Microsoft.Update.Session;$downloader=$session.CreateUpdateDownloader();$downloader.Updates=$dlCollection;$downloader.Download()|Out-Null;Pump-UI;Set-StepProgress 50 70 85;Log "    [OK] Download completato."}else{Log "    [i] Tutti gia scaricati."}
            Flush-LogBuffer;Pump-UI
            $installCollection=New-Object -ComObject Microsoft.Update.UpdateColl
            for($i=0;$i -lt $sr.Updates.Count;$i++){$u=$sr.Updates.Item($i);if($u.IsDownloaded){$installCollection.Add($u)|Out-Null}}
            if($installCollection.Count -gt 0){
                Log "    [PKG] Installazione...";Flush-LogBuffer;Pump-UI
                $session=New-Object -ComObject Microsoft.Update.Session;$installer=$session.CreateUpdateInstaller();$installer.Updates=$installCollection;Pump-UI;$installResult=$installer.Install();Pump-UI
                for($i=0;$i -lt $installCollection.Count;$i++){$rc=$installResult.GetUpdateResult($i).ResultCode;$status=switch($rc){2{"[OK]"}3{"[OK*]"}4{"[X]"}5{"[!]"}default{"[?]"}};Log "    $status $($installCollection.Item($i).Title)";Set-StepProgress([Math]::Round((($i+1)/$installCollection.Count)*100)) 70 85;Pump-UI}
                if($installResult.RebootRequired){Log "";Log "[!] RIAVVIO NECESSARIO."}
            }else{Log "[!] Nessun aggiornamento scaricato."}
        }
        $script:pendingUpdates=$null
    }catch{Log "[X] $($_.Exception.Message)"}
    Log "===============================================================================================";Log "";Set-StepProgress 100 70 85;Update-Status "[OK] Installazione completata" $successColor;Flush-LogBuffer;Pump-UI
}

function Run-ProcessRealtime {
    param([string]$fileName,[string]$processArguments,[string]$description,[int]$stepStart=-1,[int]$stepEnd=-1)
    Log "";Log "===============================================================================================";Log "[>] $description";Log "==============================================================================================="
    $process=$null
    try{
        Log "[CMD] $fileName $processArguments";Log ""
        $psi=New-Object System.Diagnostics.ProcessStartInfo;$psi.FileName=$fileName;$psi.Arguments=$processArguments
        $psi.UseShellExecute=$false;$psi.RedirectStandardOutput=$true;$psi.RedirectStandardError=$true
        $psi.CreateNoWindow=$true;$psi.StandardOutputEncoding=[System.Text.Encoding]::UTF8;$psi.StandardErrorEncoding=[System.Text.Encoding]::UTF8
        $process=New-Object System.Diagnostics.Process;$process.StartInfo=$psi;$process.EnableRaisingEvents=$true
        $outputQueue=[System.Collections.Concurrent.ConcurrentQueue[string]]::new();$errorQueue=[System.Collections.Concurrent.ConcurrentQueue[string]]::new()
        $outHandler=Register-ObjectEvent -InputObject $process -EventName OutputDataReceived -Action {$l=$Event.SourceEventArgs.Data;if($null -ne $l){$Event.MessageData.Enqueue($l)}} -MessageData $outputQueue
        $errHandler=Register-ObjectEvent -InputObject $process -EventName ErrorDataReceived -Action {$l=$Event.SourceEventArgs.Data;if($null -ne $l -and $l.Trim()){$Event.MessageData.Enqueue($l)}} -MessageData $errorQueue
        $process.Start()|Out-Null;$process.BeginOutputReadLine();$process.BeginErrorReadLine()
        while(-not $process.HasExited -or $outputQueue.Count -gt 0){
            if($script:cancelRequested){try{$process.Kill()}catch{};Log "[STOP] Processo terminato.";$script:cancelRequested=$false;break}
            $line=$null;$cnt=0;while($outputQueue.TryDequeue([ref]$line) -and $cnt -lt 30){$cnt++;if(-not $line -or(Is-SpinnerLine $line)){continue};$lp=Get-PercentFromLine $line;if($null -ne $lp -and $stepStart -ge 0 -and $stepEnd -ge 0){Set-StepProgress $lp $stepStart $stepEnd};$f=Format-LogLine $line;if($f){Log $f}}
            $errLine=$null;while($errorQueue.TryDequeue([ref]$errLine)){if($errLine -and $errLine.Trim() -and -not(Is-SpinnerLine $errLine)){Log " [X] $($errLine.Trim())"}}
            Flush-LogBuffer;Pump-UI;if(-not $process.HasExited){Start-Sleep -Milliseconds 50}
        }
        Start-Sleep -Milliseconds 200
        $line=$null;while($outputQueue.TryDequeue([ref]$line)){if($line -and -not(Is-SpinnerLine $line)){$f=Format-LogLine $line;if($f){Log $f}}}
        $errLine=$null;while($errorQueue.TryDequeue([ref]$errLine)){if($errLine -and $errLine.Trim()){Log " [X] $($errLine.Trim())"}}
        Unregister-Event -SourceIdentifier $outHandler.Name -ErrorAction SilentlyContinue;Unregister-Event -SourceIdentifier $errHandler.Name -ErrorAction SilentlyContinue
        Remove-Job $outHandler -Force -ErrorAction SilentlyContinue;Remove-Job $errHandler -Force -ErrorAction SilentlyContinue
        $ec=$process.ExitCode;Log "";if($stepStart -ge 0 -and $stepEnd -ge 0 -and $ec -eq 0){Set-StepProgress 100 $stepStart $stepEnd};if($ec -eq 0){Log "[OK] Completato."}else{Log "[!] Codice: $ec"}
        Flush-LogBuffer;return $ec
    }catch{Log "[X] $($_.Exception.Message)";Flush-LogBuffer;return -1}
    finally{if($process){try{$process.Dispose()}catch{}}}
}

function Do-Winget { if($script:isClosing -or(Test-Cancel)){return};if(-not(Test-WingetAvailable)){return};Update-Progress 10;Update-Status "[...] Winget Upgrade..." $fgColor;Flush-LogBuffer;Pump-UI;Run-ProcessRealtime "winget" "upgrade --all --force --accept-package-agreements --accept-source-agreements --include-unknown" "Winget - Tutti i pacchetti" 10 25;Set-StepProgress 100 10 25;Update-Status "[OK] Winget completato" $successColor;Flush-LogBuffer;Pump-UI }
function Do-StoreUpdate { if($script:isClosing -or(Test-Cancel)){return};if(-not(Test-WingetAvailable)){return};Update-Progress 30;Update-Status "[...] Store Update..." $fgColor;Flush-LogBuffer;Pump-UI;Run-ProcessRealtime "winget" "upgrade --source msstore --all --accept-package-agreements --accept-source-agreements" "Microsoft Store apps" 30 40;try{Start-Process "ms-windows-store://downloadsandupdates" -WindowStyle Hidden -ErrorAction SilentlyContinue}catch{};Log "    [OK] Store attivato in background.";Set-StepProgress 100 30 40;Update-Status "[OK] Store aggiornato" $successColor;Flush-LogBuffer;Pump-UI }
function Do-CleanTemp { if($script:isClosing -or(Test-Cancel)){return};Log "";Log "===============================================================================================";Log "[>] PULIZIA: Temp";Log "===============================================================================================";Update-Progress 90;Update-Status "[...] Pulizia temp..." $fgColor;Flush-LogBuffer;Pump-UI;$paths=@(@{Path=$env:TEMP;Name="Temp utente"},@{Path="$env:LOCALAPPDATA\Temp";Name="Temp locale"},@{Path="$env:USERPROFILE\AppData\Local\Microsoft\Windows\INetCache";Name="Cache Internet"},@{Path="$env:USERPROFILE\AppData\Local\Microsoft\Windows\WebCache";Name="Web Cache"},@{Path="$env:USERPROFILE\AppData\Local\CrashDumps";Name="Crash Dumps"});if($isAdmin){$paths+=@{Path="$env:WINDIR\Temp";Name="Temp Windows"}};$totalFreed=[long]0;foreach($p in $paths){if(Test-Cancel){return};if(Test-Path $p.Path){try{$items=Get-ChildItem -Path $p.Path -Force -Recurse -ErrorAction SilentlyContinue;$size=($items|Measure-Object -Property Length -Sum -ErrorAction SilentlyContinue).Sum;if(-not $size){$size=0};$cnt=($items|Measure-Object).Count;if($cnt -gt 0){Remove-Item "$($p.Path)\*" -Recurse -Force -ErrorAction SilentlyContinue;$totalFreed+=$size};Log "    [$($p.Name)] $cnt file, $([Math]::Round($size/1MB,1)) MB"}catch{}}; Pump-UI};$mb=[Math]::Round($totalFreed/1MB,2);Log "";Log "[OK] Liberati: $mb MB";Log "===============================================================================================";Log "";Update-Status "[OK] Pulizia ($mb MB)" $successColor;Flush-LogBuffer;Pump-UI }
function Do-DiskCleanup { if($script:isClosing -or(Test-Cancel)){return};if(-not $isAdmin){Log "[X] Servono privilegi admin.";Update-Status "[!] Privilegi insufficienti" $warningColor;Flush-LogBuffer;return};Update-Status "[...] Disk Cleanup..." $maintColor;Flush-LogBuffer;Pump-UI;try{$cleanPath="HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\VolumeCaches";if(Test-Path $cleanPath){Get-ChildItem $cleanPath -ErrorAction SilentlyContinue|ForEach-Object{Set-ItemProperty -Path $_.PSPath -Name "StateFlags0100" -Value 2 -ErrorAction SilentlyContinue}};Run-ProcessRealtime "cleanmgr" "/sagerun:100" "Pulizia disco avanzata" 80 95}catch{Log "[X] $($_.Exception.Message)"};Update-Status "[OK] Disk Cleanup" $successColor;Flush-LogBuffer;Pump-UI }
function Do-FlushDNS { if($script:isClosing -or(Test-Cancel)){return};Update-Status "[...] Flush DNS..." $networkColor;Flush-LogBuffer;Pump-UI;Log "";Log "===============================================================================================";Log "[>] Flush DNS";Log "===============================================================================================";try{$o=& ipconfig /flushdns 2>&1;Log-Output $o;Log "[OK] DNS svuotata."}catch{Log "[X] $($_.Exception.Message)"};Log "===============================================================================================";Log "";Update-Status "[OK] DNS svuotata" $successColor;Flush-LogBuffer;Pump-UI }
function Do-RenewIP { if($script:isClosing -or(Test-Cancel)){return};Update-Status "[...] Renew IP..." $networkColor;Flush-LogBuffer;Pump-UI;Log "";Log "===============================================================================================";Log "[>] Rinnovo IP";Log "===============================================================================================";try{$o1=& ipconfig /release 2>&1;Log-Output $o1;Pump-UI;Start-Sleep 2;Pump-UI;$o2=& ipconfig /renew 2>&1;Log-Output $o2;Log "[OK] IP rinnovato."}catch{Log "[X] $($_.Exception.Message)"};Log "===============================================================================================";Log "";Update-Status "[OK] IP rinnovato" $successColor;Flush-LogBuffer;Pump-UI }
function Do-InfoIP { if($script:isClosing -or(Test-Cancel)){return};Update-Status "[...] Info IP..." $infoColor;Flush-LogBuffer;Pump-UI;Log "";Log "===============================================================================================";Log "[>] Info Rete";Log "===============================================================================================";try{$o=& ipconfig /all 2>&1;foreach($l in $o){Log "    $l"}}catch{Log "[X] $($_.Exception.Message)"};Log "===============================================================================================";Log "";Update-Status "[OK] Info IP" $successColor;Flush-LogBuffer;Pump-UI }
function Do-ResetWinsock { if($script:isClosing -or(Test-Cancel)){return};Update-Status "[...] Reset Winsock..." $networkColor;Flush-LogBuffer;Pump-UI;if(-not $isAdmin){Log "[X] Servono privilegi admin.";Update-Status "[!] Privilegi insufficienti" $warningColor;Flush-LogBuffer;return};Log "";Log "===============================================================================================";Log "[>] Reset Winsock";Log "===============================================================================================";try{$o1=& netsh winsock reset 2>&1;Log-Output $o1;Pump-UI;$o2=& netsh int ip reset 2>&1;Log-Output $o2;Log "[OK] Winsock resettato. RIAVVIO CONSIGLIATO."}catch{Log "[X] $($_.Exception.Message)"};Log "===============================================================================================";Log "";Update-Status "[OK] Winsock reset" $successColor;Flush-LogBuffer;Pump-UI }
function Do-WifiPasswords { if($script:isClosing -or(Test-Cancel)){return};Update-Status "[...] Password Wi-Fi..." $networkColor;Flush-LogBuffer;Pump-UI;Log "";Log "===============================================================================================";Log "[>] Password Wi-Fi salvate";Log "===============================================================================================";try{$profiles=& netsh wlan show profiles 2>&1;$profileMatches=$profiles|Select-String "Tutti i profili utente\s*:\s*(.+)$|Profilo tutti gli utenti\s*:\s*(.+)$|All User Profile\s*:\s*(.+)$|User Profile\s*:\s*(.+)$|Profile\s*:\s*(.+)$";if(-not $profileMatches){Log "[i] Nessun profilo Wi-Fi trovato.";Log "===============================================================================================";Update-Status "[OK] Nessun profilo" $successColor;Flush-LogBuffer;Pump-UI;return};$names=foreach($m in $profileMatches){$m.Matches[0].Groups|Where-Object{$_.Value -and $_.Value.Trim() -ne ""}|Select-Object -Skip 1 -First 1|ForEach-Object{$_.Value.Trim()}};Log "[OK] $($names.Count) reti trovate:";Log "";foreach($name in $names){if(Test-Cancel){return};$detail=& netsh wlan show profile name="$name" key=clear 2>&1;$kl=($detail|Select-String "Contenuto chiave\s*:\s*(.+)$|Key Content\s*:\s*(.+)$");$pw="N/D";if($kl){$match=$kl.Matches[0];$pw1=$match.Groups[1].Value.Trim();$pw2=$match.Groups[2].Value.Trim();if($pw1){$pw=$pw1}elseif($pw2){$pw=$pw2}};Log "    SSID: $name | Password: $pw";Pump-UI}}catch{Log "[X] $($_.Exception.Message)"};Log "";Log "===============================================================================================";Update-Status "[OK] Password Wi-Fi" $successColor;Flush-LogBuffer;Pump-UI }
function Do-SpeedTest { if($script:isClosing -or(Test-Cancel)){return};Update-Status "[...] Test ping..." $networkColor;Flush-LogBuffer;Pump-UI;Log "";Log "===============================================================================================";Log "[>] Test ping rete";Log "===============================================================================================";$targets=@(@{Name="Google DNS";IP="8.8.8.8"},@{Name="Cloudflare";IP="1.1.1.1"},@{Name="OpenDNS";IP="208.67.222.222"},@{Name="Google.com";IP="google.com"});foreach($t in $targets){if(Test-Cancel){return};try{$ping=Test-Connection -ComputerName $t.IP -Count 3 -ErrorAction Stop;$prop=$script:pingProperty;$avg=[Math]::Round(($ping|Measure-Object -Property $prop -Average).Average,1);$min=[Math]::Round(($ping|Measure-Object -Property $prop -Minimum).Minimum,1);$max=[Math]::Round(($ping|Measure-Object -Property $prop -Maximum).Maximum,1);Log "    $($t.Name) ($($t.IP)): avg=${avg}ms min=${min}ms max=${max}ms"}catch{Log "    [X] $($t.Name): non raggiungibile"};Pump-UI};Log "===============================================================================================";Log "";Update-Status "[OK] Test rete" $successColor;Flush-LogBuffer;Pump-UI }
function Do-SpeedInternet { if($script:isClosing -or(Test-Cancel)){return};Update-Status "[...] Speedtest Cloudflare..." $networkColor;Flush-LogBuffer;Pump-UI;Log "";Log "===============================================================================================";Log "[>] Speedtest Internet (Cloudflare)";Log "===============================================================================================";[Net.ServicePointManager]::SecurityProtocol=[Net.SecurityProtocolType]::Tls12;Log "    [1/3] Test latenza...";Flush-LogBuffer;Pump-UI;$latency=0;try{$swPing=[System.Diagnostics.Stopwatch]::StartNew();Invoke-WebRequest -Uri "https://speed.cloudflare.com/__down?bytes=0" -Method Get -TimeoutSec 5 -UseBasicParsing|Out-Null;$swPing.Stop();$latency=[Math]::Round($swPing.Elapsed.TotalMilliseconds,2);Log "    Ping HTTP: $latency ms"}catch{Log "    [X] Ping fallito: $($_.Exception.Message)"};Flush-LogBuffer;Pump-UI;if(Test-Cancel){return};Log "    [2/3] Test download (20 MB)...";Flush-LogBuffer;Pump-UI;$downloadMbps=0;try{$sw=[System.Diagnostics.Stopwatch]::StartNew();$data=Invoke-WebRequest -Uri "https://speed.cloudflare.com/__down?bytes=20000000" -Method Get -TimeoutSec 30 -UseBasicParsing;$sw.Stop();$bytes=$data.RawContentLength;if($bytes -and $sw.Elapsed.TotalSeconds -gt 0){$downloadMbps=[Math]::Round((($bytes*8)/1MB)/$sw.Elapsed.TotalSeconds,2)};Log "    Download: $downloadMbps Mbps ($([Math]::Round($sw.Elapsed.TotalSeconds,2))s)"}catch{Log "    [X] Download fallito: $($_.Exception.Message)"};Flush-LogBuffer;Pump-UI;if(Test-Cancel){return};Log "    [3/3] Test upload (5 MB)...";Flush-LogBuffer;Pump-UI;$uploadMbps=0;try{$buffer=New-Object byte[](5MB);(New-Object Random).NextBytes($buffer);$sw=[System.Diagnostics.Stopwatch]::StartNew();Invoke-WebRequest -Uri "https://speed.cloudflare.com/__up" -Method Post -Body $buffer -TimeoutSec 30 -UseBasicParsing|Out-Null;$sw.Stop();if($sw.Elapsed.TotalSeconds -gt 0){$uploadMbps=[Math]::Round((5*8)/$sw.Elapsed.TotalSeconds,2)};Log "    Upload:   $uploadMbps Mbps ($([Math]::Round($sw.Elapsed.TotalSeconds,2))s)"}catch{Log "    [X] Upload fallito: $($_.Exception.Message)"};Flush-LogBuffer;Pump-UI;Log "";Log "    ============================================";Log "    RISULTATI SPEEDTEST (Cloudflare)";Log "    ============================================";Log "    Ping:     $latency ms";Log "    Download: $downloadMbps Mbps";Log "    Upload:   $uploadMbps Mbps";Log "    ============================================";Log "";Log "===============================================================================================";Log "";Update-Status "[OK] DL ${downloadMbps} / UP ${uploadMbps} Mbps" $successColor;Flush-LogBuffer;Pump-UI }
function Do-RepairSystem { if($script:isClosing -or(Test-Cancel)){return};if(-not $isAdmin){Log "[X] Servono privilegi admin.";Update-Status "[!] Privilegi insufficienti" $warningColor;Flush-LogBuffer;return};Update-Status "[...] SFC..." $repairColor;Flush-LogBuffer;Pump-UI;Run-ProcessRealtime "sfc" "/scannow" "SFC - System File Checker" 20 50;if(Test-Cancel){return};Update-Status "[...] DISM..." $repairColor;Flush-LogBuffer;Pump-UI;Run-ProcessRealtime "DISM" "/Online /Cleanup-Image /RestoreHealth" "DISM - Restore Health" 50 85;Update-Status "[OK] Riparazione completata" $successColor;Flush-LogBuffer;Pump-UI }
function Do-RestorePoint { if($script:isClosing -or(Test-Cancel)){return};if(-not $isAdmin){Log "[X] Servono privilegi admin.";Update-Status "[!] Privilegi insufficienti" $warningColor;Flush-LogBuffer;return};Update-Status "[...] Punto di ripristino..." $repairColor;Flush-LogBuffer;Pump-UI;Log "";Log "===============================================================================================";Log "[>] Creazione punto di ripristino";Log "===============================================================================================";try{Enable-ComputerRestore -Drive "$env:SystemDrive\" -ErrorAction SilentlyContinue;Pump-UI;Checkpoint-Computer -Description "Manutenzione PRO MAX - $(Get-Date -Format 'dd/MM/yyyy HH:mm')" -RestorePointType MODIFY_SETTINGS -ErrorAction Stop;Log "[OK] Punto di ripristino creato."}catch{if($_.Exception.Message -match "frequenza|frequency|1410"){Log "[!] Windows limita a 1 punto ogni 24h."}else{Log "[X] $($_.Exception.Message)"}};Log "===============================================================================================";Log "";Update-Status "[OK] Punto ripristino" $successColor;Flush-LogBuffer;Pump-UI }
function Do-SecurityScan { if($script:isClosing -or(Test-Cancel)){return};Update-Status "[...] Defender Scan..." $securityColor;Flush-LogBuffer;Pump-UI;$mpCmd="$env:ProgramFiles\Windows Defender\MpCmdRun.exe";if(-not(Test-Path $mpCmd)){$mpCmd="${env:ProgramFiles(x86)}\Windows Defender\MpCmdRun.exe"};if(-not(Test-Path $mpCmd)){$platform=Get-ChildItem "$env:ProgramData\Microsoft\Windows Defender\Platform" -Directory -ErrorAction SilentlyContinue|Sort-Object Name -Descending|Select-Object -First 1;if($platform){$mpCmd=Join-Path $platform.FullName "MpCmdRun.exe"}};if(Test-Path $mpCmd){Run-ProcessRealtime $mpCmd "-Scan -ScanType 1" "Windows Defender - Quick Scan" 30 80}else{Log "[X] MpCmdRun.exe non trovato."};Update-Status "[OK] Scansione completata" $successColor;Flush-LogBuffer;Pump-UI }
function Do-UnlockCPU { if($script:isClosing -or(Test-Cancel)){return};if(-not $isAdmin){Log "[X] Servono privilegi admin.";Update-Status "[!] Privilegi insufficienti" $warningColor;Flush-LogBuffer;return};Update-Status "[...] Sblocco CPU..." $cpuColor;Flush-LogBuffer;Pump-UI;Log "";Log "===============================================================================================";Log "[>] Sblocco opzioni CPU (Power Settings)";Log "===============================================================================================";$cpuCat="54533251-82be-4824-96c1-47b60b740d00";$cpuSettings=@(@{GUID="be337238-0d82-4146-a960-4f3749d470c7";Desc="Boost mode"},@{GUID="5d76a2ca-e8c0-402f-a133-2158492d58ad";Desc="Idle disable"},@{GUID="893dee8e-2bef-41e0-89c6-b55d0929964c";Desc="Min processor state"},@{GUID="bc5038f7-23e0-4960-96da-33abaf5935ec";Desc="Max processor state"},@{GUID="0cc5b647-c1df-4637-891a-dec35c318583";Desc="Parking min cores"},@{GUID="ea062031-0e34-4ff1-9b6d-eb1059334028";Desc="Parking max cores"},@{GUID="68dd2f27-a4ce-4e11-8487-3794e4135dfa";Desc="Parking increase threshold"},@{GUID="2ddd5a84-5a71-437e-912a-db0b8c788732";Desc="Parking decrease threshold"},@{GUID="4b92d758-5a24-4851-a470-815d78aee119";Desc="Parking increase time"},@{GUID="d6ba4903-386f-4c2c-8adb-5c21b3328d25";Desc="Parking decrease time"},@{GUID="45bcc044-d885-43e2-8605-ee0ec6e96b59";Desc="Energy perf preference"},@{GUID="36687f9e-e3a5-4dbf-b1dc-15eb381c6863";Desc="Autonomous mode"},@{GUID="cfeda3d0-7697-4566-a922-a9086cd49dfa";Desc="Duty cycling"},@{GUID="fddc842b-8364-4edc-94cf-c17f60de1c80";Desc="Perf autonomous mode"});$unlocked=0;foreach($s in $cpuSettings){if(Test-Cancel){return};$path="HKLM:\SYSTEM\CurrentControlSet\Control\Power\PowerSettings\$cpuCat\$($s.GUID)";if(Test-Path $path){try{Set-ItemProperty -Path $path -Name "Attributes" -Value 2 -ErrorAction Stop;Log "    [OK] $($s.Desc)";$unlocked++}catch{Log "    [X] $($s.Desc): $($_.Exception.Message)"}}else{Log "    [--] $($s.Desc) (non presente)"};Pump-UI};Log "";Log "[OK] Sbloccate $unlocked/$($cpuSettings.Count).";Log "===============================================================================================";Log "";Update-Status "[OK] CPU unlock ($unlocked)" $successColor;Flush-LogBuffer;Pump-UI }
function Do-RemoteAssist { if($script:isClosing -or(Test-Cancel)){return};Update-Status "[...] Assistenza Remota..." $remoteColor;Flush-LogBuffer;Pump-UI;Log "";Log "===============================================================================================";Log "[>] Assistenza Remota (RustDesk)";Log "===============================================================================================";$rustdeskUrl="https://github.com/rustdesk/rustdesk/releases/download/1.2.2/rustdesk-1.2.2-x86_64.exe";$tempPath="C:\Temp\RustDeskPortable";$exePath=Join-Path $tempPath "rustdesk.exe";if(!(Test-Path $tempPath)){New-Item -ItemType Directory -Force -Path $tempPath|Out-Null;Log "    [i] Cartella: $tempPath"};if(!(Test-Path $exePath)){Log "    [DL] Download RustDesk...";Flush-LogBuffer;Pump-UI;try{[Net.ServicePointManager]::SecurityProtocol=[Net.SecurityProtocolType]::Tls12;Invoke-WebRequest $rustdeskUrl -OutFile $exePath -UseBasicParsing -ErrorAction Stop;Log "    [OK] Download completato."}catch{Log "    [X] Download fallito: $($_.Exception.Message)";Log "===============================================================================================";Log "";Update-Status "[X] Download fallito" $exitColor;Flush-LogBuffer;Pump-UI;return}}else{Log "    [i] RustDesk gia presente."};Flush-LogBuffer;Pump-UI;Log "    [i] Avvio RustDesk...";Flush-LogBuffer;Pump-UI;try{Start-Process $exePath -ErrorAction Stop;Start-Sleep -Seconds 4;Pump-UI;$id=& $exePath --get-id 2>$null;$pw=& $exePath --get-password 2>$null;Log "";Log "    ============================================";Log "    ASSISTENZA REMOTA";Log "    ============================================";if($id){Log "    ID:       $id"}else{Log "    ID:       (controlla RustDesk)"};if($pw){Log "    Password: $pw"}else{Log "    Password: (controlla RustDesk)"};Log "    ============================================";Log "";Log "    [i] Comunica ID e Password al tecnico."}catch{Log "    [X] Errore: $($_.Exception.Message)"};Log "===============================================================================================";Log "";Update-Status "[OK] RustDesk avviato" $successColor;Flush-LogBuffer;Pump-UI }
function Do-SystemInfo { if($script:isClosing -or(Test-Cancel)){return};Update-Status "[...] Info sistema..." $infoColor;Flush-LogBuffer;Pump-UI;Log "";Log "===============================================================================================";Log "[>] Informazioni Sistema";Log "===============================================================================================";try{$os=Get-CimInstance Win32_OperatingSystem;$cpu=Get-CimInstance Win32_Processor|Select-Object -First 1;$ram=Get-CimInstance Win32_PhysicalMemory;$gpu=Get-CimInstance Win32_VideoController|Select-Object -First 1;$disk=Get-CimInstance Win32_LogicalDisk -Filter "DriveType=3";$bios=Get-CimInstance Win32_BIOS;$mb=Get-CimInstance Win32_BaseBoard;Pump-UI;Log "    OS:          $($os.Caption) $($os.OSArchitecture)";Log "    Build:       $($os.BuildNumber) ($($os.Version))";Log "    CPU:         $($cpu.Name)";Log "    Core/Thread: $($cpu.NumberOfCores)/$($cpu.NumberOfLogicalProcessors)";$totalRam=[Math]::Round(($ram|Measure-Object Capacity -Sum).Sum/1GB,1);Log "    RAM:         $totalRam GB";Log "    GPU:         $($gpu.Name)";Log "    BIOS:        $($bios.Manufacturer) - $($bios.SMBIOSBIOSVersion)";Log "    Scheda:      $($mb.Manufacturer) $($mb.Product)";Log "";foreach($d in $disk){$free=[Math]::Round($d.FreeSpace/1GB,1);$total=[Math]::Round($d.Size/1GB,1);$pct=if($total -gt 0){[Math]::Round((($total-$free)/$total)*100)}else{0};Log "    Disco $($d.DeviceID) $([Math]::Round($total-$free,1))/$total GB ($pct%)"}}catch{Log "[X] $($_.Exception.Message)"};Log "===============================================================================================";Log "";Update-Status "[OK] Info sistema" $successColor;Flush-LogBuffer;Pump-UI }
function Do-BatteryReport { if($script:isClosing -or(Test-Cancel)){return};Update-Status "[...] Batteria..." $infoColor;Flush-LogBuffer;Pump-UI;Log "";Log "===============================================================================================";Log "[>] Report Batteria";Log "===============================================================================================";try{$rp=Join-Path $tempDir "battery-report.html";$o=& powercfg /batteryreport /output "$rp" 2>&1;Log-Output $o;Pump-UI;if(Test-Path $rp){Log "[OK] Report: $rp";Start-Process $rp;Log "    [i] Aperto nel browser."}else{Log "[!] Nessuna batteria rilevata."}}catch{Log "[X] $($_.Exception.Message)"};Log "===============================================================================================";Log "";Update-Status "[OK] Batteria" $successColor;Flush-LogBuffer;Pump-UI }
function Do-Uptime { if($script:isClosing -or(Test-Cancel)){return};Update-Status "[...] Uptime..." $infoColor;Flush-LogBuffer;Pump-UI;Log "";Log "===============================================================================================";Log "[>] Uptime";Log "===============================================================================================";try{$os=Get-CimInstance Win32_OperatingSystem;$boot=$os.LastBootUpTime;$up=(Get-Date)-$boot;Log "    Ultimo avvio:  $($boot.ToString('dd/MM/yyyy HH:mm:ss'))";Log "    Uptime:        $($up.Days)g $($up.Hours)h $($up.Minutes)m";if($up.Days -gt 7){Log "    [!] Riavvio consigliato."}}catch{Log "[X] $($_.Exception.Message)"};Log "===============================================================================================";Log "";Update-Status "[OK] Uptime" $successColor;Flush-LogBuffer;Pump-UI }
function Do-TopProcesses { if($script:isClosing -or(Test-Cancel)){return};Update-Status "[...] Processi..." $cpuColor;Flush-LogBuffer;Pump-UI;Log "";Log "===============================================================================================";Log "[>] Top 15 processi CPU";Log "===============================================================================================";try{$procs=Get-Process|Where-Object{$_.CPU -gt 0}|Sort-Object CPU -Descending|Select-Object -First 15;Log("    {0,-32} {1,10} {2,10}" -f "PROCESSO","CPU (s)","RAM (MB)");Log("    {0,-32} {1,10} {2,10}" -f ("-"*32),("-"*10),("-"*10));foreach($proc in $procs){Log("    {0,-32} {1,10} {2,10}" -f $proc.ProcessName,[Math]::Round($proc.CPU,1),[Math]::Round($proc.WorkingSet64/1MB,1))}}catch{Log "[X] $($_.Exception.Message)"};Log "===============================================================================================";Log "";Update-Status "[OK] Processi" $successColor;Flush-LogBuffer;Pump-UI }
function Do-StartupPrograms { if($script:isClosing -or(Test-Cancel)){return};Update-Status "[...] Startup..." $cpuColor;Flush-LogBuffer;Pump-UI;Log "";Log "===============================================================================================";Log "[>] Programmi all'avvio";Log "===============================================================================================";try{$startup=Get-CimInstance Win32_StartupCommand -ErrorAction Stop;if($startup){foreach($s in $startup){$cmd=if($s.Command.Length -gt 50){$s.Command.Substring(0,47)+"..."}else{$s.Command};Log "    $($s.Name) | $cmd"}};Log "";Log "    --- HKLM\Run ---";$reg=Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Run" -ErrorAction SilentlyContinue;if($reg){$reg.PSObject.Properties|Where-Object{$_.Name -notmatch '^PS'}|ForEach-Object{Log "    $($_.Name)"}};Log "    --- HKCU\Run ---";$regU=Get-ItemProperty "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Run" -ErrorAction SilentlyContinue;if($regU){$regU.PSObject.Properties|Where-Object{$_.Name -notmatch '^PS'}|ForEach-Object{Log "    $($_.Name)"}}}catch{Log "[X] $($_.Exception.Message)"};Log "===============================================================================================";Log "";Update-Status "[OK] Startup" $successColor;Flush-LogBuffer;Pump-UI }
function Do-DiskSpace { if($script:isClosing -or(Test-Cancel)){return};Update-Status "[...] Disco..." $maintColor;Flush-LogBuffer;Pump-UI;Log "";Log "===============================================================================================";Log "[>] Spazio disco";Log "===============================================================================================";try{$up=$env:USERPROFILE;$dr=$env:SystemDrive+"\";$folders=@("$up\Downloads","$up\Desktop","$up\Documents","$up\Videos","$up\AppData\Local","$up\AppData\Roaming","${dr}Program Files","${dr}Program Files (x86)","${dr}Windows\Temp","${dr}Windows\SoftwareDistribution");$results=@();foreach($f in $folders){if(Test-Cancel){return};if(Test-Path $f){try{$sz=(Get-ChildItem $f -Recurse -Force -ErrorAction SilentlyContinue|Measure-Object -Property Length -Sum -ErrorAction SilentlyContinue).Sum;if(-not $sz){$sz=0};$results+=@{P=$f;S=$sz}}catch{$results+=@{P=$f;S=0}}};Pump-UI};$results=$results|Sort-Object{$_.S} -Descending;foreach($r in $results){$d=if($r.S -ge 1GB){"$([Math]::Round($r.S/1GB,2)) GB"}else{"$([Math]::Round($r.S/1MB,0)) MB"};$sp=$r.P.Replace($up,"~").Replace($dr,"$($env:SystemDrive)\");Log("    {0,-48} {1,10}" -f $sp,$d)}}catch{Log "[X] $($_.Exception.Message)"};Log "===============================================================================================";Log "";Update-Status "[OK] Disco" $successColor;Flush-LogBuffer;Pump-UI }
function Do-EventLogErrors { if($script:isClosing -or(Test-Cancel)){return};Update-Status "[...] Event Log..." $securityColor;Flush-LogBuffer;Pump-UI;Log "";Log "===============================================================================================";Log "[>] Errori critici (7gg)";Log "===============================================================================================";try{$events=Get-WinEvent -FilterHashtable @{LogName='System';Level=1,2;StartTime=(Get-Date).AddDays(-7)} -MaxEvents 20 -ErrorAction Stop;if($events){foreach($ev in $events){$msg=($ev.Message -split "`n")[0];if($msg.Length -gt 75){$msg=$msg.Substring(0,72)+"..."};Log "    $($ev.TimeCreated.ToString('dd/MM HH:mm')) | $($ev.ProviderName)";Log "      $msg";Pump-UI}}else{Log "    [OK] Nessun errore."}}catch{if($_.Exception.Message -match "No events"){Log "    [OK] Nessun errore critico."}else{Log "[X] $($_.Exception.Message)"}};Log "===============================================================================================";Log "";Update-Status "[OK] Event Log" $successColor;Flush-LogBuffer;Pump-UI }
function Do-ServiceStatus { if($script:isClosing -or(Test-Cancel)){return};Update-Status "[...] Servizi..." $infoColor;Flush-LogBuffer;Pump-UI;Log "";Log "===============================================================================================";Log "[>] Servizi critici";Log "===============================================================================================";$svcs=@(@{N="wuauserv";D="Windows Update"},@{N="WinDefend";D="Defender"},@{N="mpssvc";D="Firewall"},@{N="BITS";D="BITS"},@{N="Spooler";D="Stampa"},@{N="Dnscache";D="DNS Client"},@{N="Dhcp";D="DHCP"},@{N="EventLog";D="Event Log"},@{N="Schedule";D="Task Scheduler"},@{N="W32Time";D="Ora Windows"});foreach($svc in $svcs){if(Test-Cancel){return};try{$s=Get-Service -Name $svc.N -ErrorAction Stop;$st=switch($s.Status){"Running"{"[OK]"}"Stopped"{"[--]"}default{"[??]"}};Log("    $st {0,-22} {1}" -f $svc.D,$s.Status)}catch{Log "    [??] $($svc.D): non trovato"};Pump-UI};Log "===============================================================================================";Log "";Update-Status "[OK] Servizi" $successColor;Flush-LogBuffer;Pump-UI }
function Do-ExportReport { if($script:isClosing -or(Test-Cancel)){return};Update-Status "[...] Export..." $infoColor;Flush-LogBuffer;Pump-UI;try{$rf=Join-Path([Environment]::GetFolderPath("Desktop")) "Manutenzione_Report_$(Get-Date -Format 'yyyyMMdd_HHmmss').txt";if($script:logBox){$script:logBox.Text|Out-File -FilePath $rf -Encoding UTF8;Log "";Log "[OK] Report: $rf";Start-Process explorer.exe -ArgumentList "/select,`"$rf`""}}catch{Log "[X] $($_.Exception.Message)"};Update-Status "[OK] Report" $successColor;Flush-LogBuffer;Pump-UI }

function Do-RunAll {
    if($script:isClosing -or(Test-Cancel)){return}
    Log "";Log "##################################################################################################";Log "#                           MANUTENZIONE COMPLETA                                                #";Log "##################################################################################################";Log ""
    Update-Progress 0;Flush-LogBuffer;Pump-UI
    Do-Winget;if(Test-Cancel){return};Do-StoreUpdate;if(Test-Cancel){return};Do-SearchWU;if(Test-Cancel){return};Do-InstallWU;if(Test-Cancel){return};Do-CleanTemp;if(Test-Cancel){return};Do-FlushDNS;if(Test-Cancel){return}
    Update-Progress 100;Log "";Log "##################################################################################################";Log "#                           COMPLETATA                                                            #";Log "##################################################################################################";Log ""
    Update-Status "[OK] Manutenzione completa!" $successColor;Flush-LogBuffer;Pump-UI
}

function Build-GUI {
    [System.Windows.Forms.Application]::EnableVisualStyles()
    $script:form=New-Object System.Windows.Forms.Form;$script:form.Text="Manutenzione PRO MAX v3.0";$script:form.Size=New-Object System.Drawing.Size(1100,680)
    $script:form.MinimumSize=New-Object System.Drawing.Size(1100,680);$script:form.MaximumSize=New-Object System.Drawing.Size(1100,680)
    $script:form.StartPosition="CenterScreen";$script:form.BackColor=$bgColor;$script:form.ForeColor=$fgColor
    $script:form.FormBorderStyle="FixedSingle";$script:form.MaximizeBox=$false;$script:form.Font=New-Object System.Drawing.Font("Segoe UI",9)
    $dbProp=$script:form.GetType().GetProperty("DoubleBuffered",[System.Reflection.BindingFlags]"Instance,NonPublic");if($dbProp){$dbProp.SetValue($script:form,$true)}
    $headerPanel=New-Object System.Windows.Forms.Panel;$headerPanel.Dock="Top";$headerPanel.Height=40;$headerPanel.BackColor=$bgPanel
    $titleLabel=New-Object System.Windows.Forms.Label;$titleLabel.Text=[char]0x26A1+" MANUTENZIONE PETERS";$titleLabel.Font=New-Object System.Drawing.Font("Segoe UI",11,[System.Drawing.FontStyle]::Bold);$titleLabel.ForeColor=$fgColor;$titleLabel.AutoSize=$true;$titleLabel.Location=New-Object System.Drawing.Point(10,9);$headerPanel.Controls.Add($titleLabel)
    $adminBadge=New-Object System.Windows.Forms.Label;$adminBadge.Font=New-Object System.Drawing.Font("Segoe UI",7.5,[System.Drawing.FontStyle]::Bold);$adminBadge.AutoSize=$true;$adminBadge.Location=New-Object System.Drawing.Point(260,13);if($isAdmin){$adminBadge.Text="ADMIN";$adminBadge.ForeColor=$successColor}else{$adminBadge.Text="UTENTE";$adminBadge.ForeColor=$warningColor};$headerPanel.Controls.Add($adminBadge)
    $psVer="PS$($PSVersionTable.PSVersion.Major).$($PSVersionTable.PSVersion.Minor)";$verLabel=New-Object System.Windows.Forms.Label;$verLabel.Text="v3.0 | $psVer";$verLabel.Font=New-Object System.Drawing.Font("Segoe UI",7);$verLabel.ForeColor=$fgDim;$verLabel.AutoSize=$true;$verLabel.Location=New-Object System.Drawing.Point(1000,13);$headerPanel.Controls.Add($verLabel)
    $script:form.Controls.Add($headerPanel)
    $sideW=290;$sidePanel=New-Object System.Windows.Forms.Panel;$sidePanel.Location=New-Object System.Drawing.Point(0,40);$sidePanel.Size=New-Object System.Drawing.Size($sideW,610);$sidePanel.BackColor=$bgPanel
    $pad=6;$gap=3;$colW=[int](($sideW-$pad*2-$gap)/2);$btnH=26;$rowGap=3;$sectionGap=2;$script:btnRow=$pad;$script:btnCol=0
    function Add-SectionLabel{param([string]$text,[System.Windows.Forms.Panel]$panel);if($script:btnCol -eq 1){$script:btnRow+=($btnH+$rowGap);$script:btnCol=0};$lbl=New-Object System.Windows.Forms.Label;$lbl.Text=$text.ToUpper();$lbl.Font=New-Object System.Drawing.Font("Segoe UI",6.5,[System.Drawing.FontStyle]::Bold);$lbl.ForeColor=$fgDim;$lbl.Size=New-Object System.Drawing.Size(($sideW-$pad*2),14);$lbl.Location=New-Object System.Drawing.Point($pad,$script:btnRow);$lbl.TextAlign="BottomLeft";$panel.Controls.Add($lbl);$script:btnRow+=(14+$sectionGap);$script:btnCol=0}
    function Add-Button2Col{param([string]$text,[System.Drawing.Color]$color,[ScriptBlock]$action,[System.Windows.Forms.Panel]$panel);$x=if($script:btnCol -eq 0){$pad}else{$pad+$colW+$gap};$btn=New-Object System.Windows.Forms.Button;$btn.Text=$text;$btn.Size=New-Object System.Drawing.Size($colW,$btnH);$btn.Location=New-Object System.Drawing.Point($x,$script:btnRow);$btn.FlatStyle="Flat";$btn.FlatAppearance.BorderSize=0;$btn.FlatAppearance.MouseOverBackColor=$btnHover;$btn.FlatAppearance.MouseDownBackColor=[System.Drawing.Color]::FromArgb(58,58,66);$btn.BackColor=$bgCard;$btn.ForeColor=$color;$btn.Font=New-Object System.Drawing.Font("Segoe UI Semibold",7.5);$btn.Cursor=[System.Windows.Forms.Cursors]::Hand;$btn.TextAlign="MiddleCenter";$btn.Add_Click($action);$panel.Controls.Add($btn);if($script:btnCol -eq 0){$script:btnCol=1}else{$script:btnCol=0;$script:btnRow+=($btnH+$rowGap)}}
    function Add-ButtonFull{param([string]$text,[System.Drawing.Color]$color,[ScriptBlock]$action,[System.Windows.Forms.Panel]$panel);if($script:btnCol -eq 1){$script:btnRow+=($btnH+$rowGap);$script:btnCol=0};$fullW=$sideW-$pad*2;$btn=New-Object System.Windows.Forms.Button;$btn.Text=$text;$btn.Size=New-Object System.Drawing.Size($fullW,$btnH);$btn.Location=New-Object System.Drawing.Point($pad,$script:btnRow);$btn.FlatStyle="Flat";$btn.FlatAppearance.BorderSize=0;$btn.FlatAppearance.MouseOverBackColor=$btnHover;$btn.FlatAppearance.MouseDownBackColor=[System.Drawing.Color]::FromArgb(58,58,66);$btn.BackColor=$bgCard;$btn.ForeColor=$color;$btn.Font=New-Object System.Drawing.Font("Segoe UI Semibold",7.5);$btn.Cursor=[System.Windows.Forms.Cursors]::Hand;$btn.TextAlign="MiddleCenter";$btn.Add_Click($action);$panel.Controls.Add($btn);$script:btnRow+=($btnH+$rowGap);$script:btnCol=0}
    Add-SectionLabel "Principale" $sidePanel
    Add-ButtonFull "$([char]0x25B6)  ESEGUI UPGRADE" $runAllColor {Do-RunAll} $sidePanel
    Add-Button2Col "Annulla" $exitColor {$script:cancelRequested=$true} $sidePanel
    Add-Button2Col "Export Report" $infoColor {Do-ExportReport} $sidePanel
    Add-SectionLabel "Aggiornamenti" $sidePanel
    Add-Button2Col "Winget" $accentColor {Do-Winget} $sidePanel
    Add-Button2Col "Store" $accentColor {Do-StoreUpdate} $sidePanel
    Add-Button2Col "Cerca WU" $infoColor {Do-SearchWU} $sidePanel
    Add-Button2Col "Installa WU" $infoColor {Do-InstallWU} $sidePanel
    Add-SectionLabel "Pulizia" $sidePanel
    Add-Button2Col "Temp" $maintColor {Do-CleanTemp} $sidePanel
    Add-Button2Col "Disk Cleanup" $maintColor {Do-DiskCleanup} $sidePanel
    Add-SectionLabel "Rete" $sidePanel
    Add-Button2Col "Flush DNS" $networkColor {Do-FlushDNS} $sidePanel
    Add-Button2Col "Renew IP" $networkColor {Do-RenewIP} $sidePanel
    Add-Button2Col "Info IP" $infoColor {Do-InfoIP} $sidePanel
    Add-Button2Col "Winsock" $networkColor {Do-ResetWinsock} $sidePanel
    Add-Button2Col "Wi-Fi Pass" $networkColor {Do-WifiPasswords} $sidePanel
    Add-Button2Col "Ping Test" $networkColor {Do-SpeedTest} $sidePanel
    Add-SectionLabel "Riparazione" $sidePanel
    Add-Button2Col "SFC + DISM" $repairColor {Do-RepairSystem} $sidePanel
    Add-Button2Col "Pt. Ripristino" $repairColor {Do-RestorePoint} $sidePanel
    Add-SectionLabel "Sicurezza" $sidePanel
    Add-Button2Col "Scan Defender" $securityColor {Do-SecurityScan} $sidePanel
    Add-Button2Col "Event Log" $securityColor {Do-EventLogErrors} $sidePanel
    Add-SectionLabel "Diagnostica" $sidePanel
    Add-Button2Col "Info Sistema" $infoColor {Do-SystemInfo} $sidePanel
    Add-Button2Col "Batteria" $infoColor {Do-BatteryReport} $sidePanel
    Add-Button2Col "Uptime" $infoColor {Do-Uptime} $sidePanel
    Add-Button2Col "Top Processi" $cpuColor {Do-TopProcesses} $sidePanel
    Add-Button2Col "Startup" $cpuColor {Do-StartupPrograms} $sidePanel
    Add-Button2Col "Spazio Disco" $maintColor {Do-DiskSpace} $sidePanel
    Add-Button2Col "Servizi" $infoColor {Do-ServiceStatus} $sidePanel
    Add-Button2Col "Speed Internet" $networkColor {Do-SpeedInternet} $sidePanel
    Add-Button2Col "CPU Unlock" $cpuColor {Do-UnlockCPU} $sidePanel
    Add-Button2Col "Assist. Remota" $remoteColor {Do-RemoteAssist} $sidePanel
    Add-SectionLabel "Sistema" $sidePanel
    Add-Button2Col "Eleva Admin" $elevateColor {Restart-AsAdmin} $sidePanel
    Add-Button2Col "Riavvia PC" $restartColor {$r=[System.Windows.Forms.MessageBox]::Show("Riavviare?","Conferma","YesNo","Warning");if($r -eq "Yes"){shutdown /r /t 5 /c "Riavvio"}} $sidePanel
    Add-ButtonFull "Esci" $exitColor {$script:isClosing=$true;$script:form.Close()} $sidePanel
    $script:form.Controls.Add($sidePanel)
    $contentX=$sideW;$contentW=1100-$sideW;$contentPanel=New-Object System.Windows.Forms.Panel;$contentPanel.Location=New-Object System.Drawing.Point($contentX,40);$contentPanel.Size=New-Object System.Drawing.Size($contentW,610);$contentPanel.BackColor=$bgColor
    $script:statusLabel=New-Object System.Windows.Forms.Label;$script:statusLabel.Text="Pronto";$script:statusLabel.Font=New-Object System.Drawing.Font("Segoe UI Semibold",9);$script:statusLabel.ForeColor=$fgDim;$script:statusLabel.Location=New-Object System.Drawing.Point(10,6);$script:statusLabel.Size=New-Object System.Drawing.Size(($contentW-60),20);$contentPanel.Controls.Add($script:statusLabel)
    $script:progressBar=New-Object System.Windows.Forms.ProgressBar;$script:progressBar.Location=New-Object System.Drawing.Point(10,30);$script:progressBar.Size=New-Object System.Drawing.Size(($contentW-60),8);$script:progressBar.Style="Continuous";$script:progressBar.Value=0;$script:progressBar.Minimum=0;$script:progressBar.Maximum=100;$contentPanel.Controls.Add($script:progressBar)
    $script:progressLabel=New-Object System.Windows.Forms.Label;$script:progressLabel.Text="0%";$script:progressLabel.Font=New-Object System.Drawing.Font("Segoe UI",7);$script:progressLabel.ForeColor=$fgDim;$script:progressLabel.Location=New-Object System.Drawing.Point(($contentW-44),28);$script:progressLabel.Size=New-Object System.Drawing.Size(36,14);$script:progressLabel.TextAlign="MiddleRight";$contentPanel.Controls.Add($script:progressLabel)
    $script:logBox=New-Object System.Windows.Forms.RichTextBox;$script:logBox.Location=New-Object System.Drawing.Point(10,44);$script:logBox.Size=New-Object System.Drawing.Size(($contentW-20),554);$script:logBox.BackColor=$logBg;$script:logBox.ForeColor=[System.Drawing.Color]::FromArgb(200,200,210);$script:logBox.Font=New-Object System.Drawing.Font("Consolas",9);$script:logBox.ReadOnly=$true;$script:logBox.BorderStyle="None";$script:logBox.ScrollBars="ForcedVertical";$script:logBox.WordWrap=$false;$script:logBox.DetectUrls=$false;$script:logBox.ShortcutsEnabled=$true;$contentPanel.Controls.Add($script:logBox)
    $script:form.Controls.Add($contentPanel)
    $script:uiTimer=New-Object System.Windows.Forms.Timer;$script:uiTimer.Interval=100;$script:uiTimer.Add_Tick({Flush-LogBuffer});$script:uiTimer.Start()
    $script:form.Add_Shown({Log "";Log " $([char]0x26A1) Manutenzione PRO MAX v3.0";Log " $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss') | $psVer";Log " Log: $logFile";Log "";if(-not $isAdmin){Log " [!] Utente standard. Usa 'Eleva Admin' per tutte le funzioni.";Log ""};Flush-LogBuffer})
    $script:form.Add_FormClosing({$script:isClosing=$true;$script:cancelRequested=$true;if($script:uiTimer){$script:uiTimer.Stop();$script:uiTimer.Dispose()}})
    [System.Windows.Forms.Application]::Run($script:form)
}

Build-GUI
